### ISSUE TITLE
Additional Instructions?

### ISSUE THREAD

**Issue by githubh18** [wulfsoft/powerpoint-3d-settings#1]
This is amazing! But how do you find the coordinates of each of the target shape points to put into the equation and how do you run this program? Thank you!

**Comment by wulfsoft** [comment]
Here's an easy way to determine the coordinates of a point on a slide in PowerPoint:

1. Create a rectangle shape and move it so it's upper-left corner is at the target point.
2. Right-click the shape and select _Size and Position_ from the context menu.
3. Find the coordinates under _Position_: (Horizontal position, Vertical position)

And here's a step-by-step guide on how to compile and run the code (using VS Code):

1. Install [.NET Core](https://microsoft.com/net/core), [Git](https://git-scm.com/), [Visual Studio Code](https://code.visualstudio.com/), and the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp).
2. Start Visual Studio Code and press **Ctrl+Shift+P** to open the _Command Palette_.
3. Type **Git: Clone** and select the command.
4. Enter the repository URL: **https://github.com/wulfsoft/powerpoint-3d-settings**
5. Select a folder under which to put the repository.
6. Open the repository and press **F5** to start the project.

Hope that helps.
