### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by githubh18** [wulfsoft/powerpoint-3d-settings#2]
Thanks for your help! We are getting the following error: 

Unable to start program:

netcoreapp2.0\powerpoint-3d-settings.dll

The system cannot find the file specified.

**Comment by wulfsoft** [comment]
Sorry, I'm unable to reproduce the issue here. "powerpoint-3d-settings.dll" is the filename of the compiled console app, not a dependency.

Do you see any compilation errors in the terminal? Or did you maybe forget to install the C# extension in VS Code?
